host1:
   name:  xxxxxxxxxxxxxxxxx
   ip: 192.168.xxx.xx
   offering: 8core8g
   template: Template-CentOS6.7
   l3network: vlan1120
   host: xxxxxxxxx
   zone: xxxxxx
   cluster: xxxxxx
   description: xxxxx
host2:
   name:  xxxxxxxxxxxxxxxxx
   ip: 192.168.xxx.xx
   offering: 8core8g
   template: Template-CentOS6.7
   l3network: vlan1120
   host: xxxxxxxxx
   zone: xxxxxx
   cluster: xxxxxx
   description: xxxxx

